---
- name: Create docker auth repo
  ansible.builtin.file:
      name: /home/docker/auth/sso
      state: directory
      owner: root
      group: root
      mode: '0755'

## Install Auth docker
- name: Install lemonldap source repo file
  ansible.builtin.copy:
      src: lemonldap-ng.list
      dest: /home/docker/auth/sso/lemonldap-ng.list
      owner: root
      group: root
      mode: '0400'
  notify: Rebuild auth docker

- name: Install Dockerfile for building lemonldap
  ansible.builtin.template:
      src: Dockerfile-sso.j2
      dest: /home/docker/auth/sso/Dockerfile
      owner: root
      group: root
      mode: '0400'
  notify: Rebuild auth docker

- name: Install nagios.conf for serving Nagios docker
  ansible.builtin.template:
      src: nagios.conf.apache2.j2
      dest: /home/docker/auth/sso/nagios.conf
      owner: root
      group: root
      mode: '0644'
  when: inventory_hostname in groups['docker_nagios']
  notify: Rebuild auth docker

- name: Install Auth docker architecture
  ansible.builtin.template:
      src: docker-compose.yaml.j2
      dest: /home/docker/auth/docker-compose.yaml
      owner: root
      group: root
      mode: '0400'
  notify: Start auth docker

## Backup Auth section
- name: Install auth backup compose file
  ansible.builtin.template:
      src: backup.yaml.j2
      dest: /home/docker/backups/backup-auth.yaml
      owner: root
      group: root
      mode: '0400'
  when: inventory_hostname in groups['maintenance_contract']

- name: Install auth backup2 compose file
  ansible.builtin.template:
      src: backup2.yaml.j2
      dest: /home/docker/backups/backup2-auth.yaml
      owner: root
      group: root
      mode: '0400'
  when: inventory_hostname in groups['maintenance_contract']

- name: Add cron job to run data backup every day
  ansible.builtin.cron:
      name: backup auth data
      minute: "45"
      hour: "00"
      job: /usr/bin/docker exec openldap slapcat -v > /home/docker/backups/ldap_backup.ldif ; chmod 400 /home/docker/backups/ldap_backup.ldif
  when: inventory_hostname in groups['maintenance_contract']

- name: Add cron job to run backup every day
  ansible.builtin.cron:
      name: push auth backup to openstack
      minute: "40"
      hour: "03"
      job: /usr/bin/docker-compose -f /home/docker/backups/backup-auth.yaml run --rm backup_auth
  when: inventory_hostname in groups['maintenance_contract']

- name: Add cron job to run backup2 every day
  ansible.builtin.cron:
      name: push auth backup2 to openstack
      minute: "50"
      hour: "00"
      job: /usr/bin/docker-compose -f /home/docker/backups/backup2-auth.yaml run --rm backup_auth
  when: inventory_hostname in groups['maintenance_contract']
